language: ruby
rvm:
- jruby-1.7.20
before_install:
- gem install bundler -v 1.10.1
script: bundle exec rspec
deploy:
  provider: rubygems
  api_key:
    secure: mSWb94XFpM2EVbNc/Si9leu4OlYrZG7+uY9qkqRc5+GLkM/7BTgQsAeXJBY/JT0vpOG1hfE4ezkrh7KBAH4MrHzbM1/XLgrjRbADAFKGExI2hdW3B3iAApTAnyhYGeKCPkIDo8TR01qhDt2caN6HnbRZLnju8Xgr6AhWo+93lGMk17Wxme7DAbXvRdaLaZ3sTtn3VKyZJW14AXjO/X1opkwTe+ko08iEbyi8JPjCqcMI0TFmqQJN0jRm2sMEQtUs1mdDuyjlT2o8ieXnEP/pNrU/vWKKwz+bYzfsE8cdyG4k6SAmurIi5zX5aFRGtEC3YegjUsvFp4L22zb5TjXJhE3RVsyHBhIV6CBK0tcqxPW7iaPwOsa5ivDfC9CfVaQ4j110wRVvihNlV2c8fOso24uohJ3bZe/rp6QpuqYK5CXOVFBkqXXGh3WKQmBTOAwVPT4lJQNBKMWt60xrh6vTe6UINgbrDURMXNTodeHVfNry0+KdXo0SS0PNRNFXG491UnpZrohSdYn10MUYL3nFta+QE7rU1FpTLSvhopeCINd3dSmq+dJ5gzymdxKH8q6A2qvN326wyrYYKWXFcL5V8o2n4Pli6d9CipVKrbA9HIIeApjb5+nioxc8p+eIflslrPT3gVH+WRfQ+geBQb7jzaL+aCVApUWWW32xE5x6Ypk=
after_success:
- coveralls
addons:
  code_climate:
    repo_token:
      secure: LgaVKGKE8OmrtOcpgs4Gfph4dMs9bNDvIUNDXgJt3xkoiy87CxNBxwB0BJNXz21SqS+MmKJKnRyRwuujM568e/Sf2cHTSlQD4HmPstu+HJ2uLx5tuaHmzz+n11MkAZZ4uhJFh3P80GIrxxw6qfR6KkdWt2HJz8BKraNsIbh6dcNllnje0Bcq4QM98ATwkIAejpquuiqn3dN9f74eZrsEr30Cdz8mpgggKB25CNiWYdgOEuI79lQvSk1ucuopsFTEkFbqwxMhFdxqjdCw6JLmJO+WIstJwZQykiqFVh0ABZsRoTFkv/JCP0xgLd5LNP+562gGutOO7KdYJXnR9R5kwENt+Bn35P9nl9O0H8G3SXdsVtwiBi15PAdE6ZSl5FvC8irdJCso5xzG8JPx5Rx0Zg7vHBXM6nciF0TiXZxQOcfMIBRQhRS0cqEcdPrggMKSSnZlaCXwTbJ+Jl5tijXX5xD042EJOB1oR5qoEwfQhGogZiumq+E9YnUgOhCRIk6UZIPCx+fshBsQco6bioPImnXw9oHvgF1RraRM2NYmm/blvo81TZ3cGVwVYRSU+LIoPaMzUgR40NePsws0YytMQsgk5ijasn19dkyEQkIv98TrcOabonWKrcnuEipATHIsU5uQPdBOCPSgxyqY/YBplSD2cT5OYdNsP5DC8AToaOg=
cache: bundler
services: redis-server